version: "2"

services:

  app:
    build: .
    image: keboola/ex-magento-v1
    tty: true
    stdin_open: true

  dev:
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./:/code
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini